### ISSUE TITLE
Update this for rocket 0.5

### ISSUE THREAD

**Issue by svenstaro** [intgr/rocket-sentry#22]
Rocket 0.5rc is out and that's what pretty much anyone will be using nowadays. It'd be great if you could update the extension to work with that. :)

**Comment by intgr** [comment]
Sure, will check it out. Feel free to remind me if I forget

**Comment by intgr** [comment]
Released with rocket-sentry 0.8.0

**Comment by svenstaro** [comment]
Very cool, will take a look!
